# (PART) Introduction {-}

# Background {-}

***

Commercial cruise voyages are a multi-billion dollar tourism industry. With any large population sourcing from numerous different networks, (regardless of their level of prior connectivity), and an extended period of high volume interaction there are natural concerns for disease spread. 

The VSP is primarily concerned with outbreaks of acute gastroenteritis, (AGE). Norovirus is the primary source of AGE across the world and thus makes up the vast majority of the outbreaks tracked by the VSP. 

### Project Intent {-}

This project’s intent is to utilize publicly available disease outbreak data from cruise ship passenger voyages to predict the likelihood of any one person getting norovirus based on what specific cruise ship they’re traveling on, the number of people traveling on the same ship, where they are going, how long the trip is, and the timeframe in which the cruise will occur. 

### Structure {-}

The structure of this document will be split into the functional units of the R scripts used in the project:

- Data Acquisition and Preparation

  - Infection Data

  - Temporal Data

  - Spatial Data

- Model Fitting

  - Program Validation

- Model Checking

  - Regressing Diagnostics
  
  - Graphical Diagnostics
  
  - Within-Sample Validation
  
  - Forecasting

- Interpretation
  
  - Closing Remarks
  
  - Source Code

## Simplifying Assumptions {-}

Simplifying assumptions are made throughout in order to achieve the end goal of this project. Aside from time and resource limitations, we have found three major factors that we believe justify the use of these assumptions.

***

##### VSP Definition of Outbreak {-}

The VSP only collects data on what is considered to be an outbreak, which they define on their website. 

 - Are on ships under VSP jurisdiction, defined as:

   - Carry 13 or more passengers

   - Have a foreign itinerary with U.S. ports.

 - Are on ships carrying 100 or more passengers.

 - Are on voyages from 3-21 days long.

 - Are on voyages where 3% or more of passengers or crew report symptoms of gastrointestinal illness to the ship’s medical staff.

We will use this as a baseline for our simplifying assumptions, and justify all of them within this definition. 

##### Spread of Norovirus {-}

Simplifying for the sake of brevity, $R_0$ is a measure of how many additional infections are caused by each existing infection, with $R_0 > 1$ being seen as a rising outbreak, $R_0 = 1$ being a stable presence of disease, and $R_0 < 1$ being a decline towards eventual die out of infection.


Norovirus, along with all other AGE agents, is problematic from the perspective of generating a consistent and realistic number for an average $R_0$ due to the prevalence of under reporting associated with this category of illness. Reported values show the range of $1 < R_0 < 8$ with a general average of $R_0 \approx 2$. Compared with seasonal influenza $1 < R_0 < 2$ and recent observations of the highest value for SARS-CoV-19 Omicron $R_0 = 1.9$, Norovirus is a highly infectious virus.


We can make the statement then, that any existence of a single case of Norovirus on a cruise vessel will result in an outbreak given that the virus travels fast enough that traditional outbreak control measures won't prevent the VSP definition of an outbreak from occurring by the time symptoms become noticeable enough to warrant action being taken.


##### The Jones Act and The Passenger Vessel Services Act {-}

These maritime laws paint two restrictions on cruise ships simultaneously. 

- Any vessel carrying merchandise between U.S. ports must be built, owned, and operated by U.S. Citizens, as well as constructed out of U.S. owned materials. 

- Foreign flagged ships must start and end their journey at the same port provided they began in a U.S. port, and must have a distant foreign port at part of their journey. 

These restrictions in practice result in a system used by most cruise liners.

- Almost all cruise ships have U.S. ports.
- Almost all cruise ships have foreign ports.
- Almost all cruise ships start and end at the same location.

We believe that this justifies the sole use of VSP data for modeling the totality of Norovirus outbreaks on cruise vessels, due to a negligibly small population of cruise voyages having no interaction with U.S. ports at any given time.

***