name: publish bookdown

on:
  push:
    branches:
      - main
      - release/*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2

    - name: setup R
      uses: r-lib/actions/setup-r@v2

    - name: cache R packages
      uses: actions/cache@v2
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION', '**/renv.lock') }}
        restore-keys: ${{ runner.os }}-r-

    - name: install system dependencies
      run: sudo apt-get install -y libcurl4-openssl-dev libssl-dev

    - name: install pak and dependencies
      run: |
        Rscript -e "install.packages('pak')"
        Rscript -e "pak::pkg_install('rstudio/bookdown')"

    - name: build book
      run: |
        cd Cruise_Model
        Rscript -e "rmarkdown::render_site(output_format = 'bookdown::gitbook', encoding = 'UTF-8')

    - name: deploy to the hub pages
      uses: Cecilapp/GitHub-Pages-deploy@master
      with:
        EMAIL: ${{ secrets.RM_S }}
        github_token: ${{ secrets.PHOE_BE }}
        BUILD_DIR: ./_book